YeetPostV1_4/YeetPostV1_4/Controllers/YeetController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
//using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using YeetPostV1_4.Models;
using YeetPostV1_4.ViewModel;
using YeetPostV1_4.Data;
using Newtonsoft.Json;
//using Microsoft.AspNet.Identity; // NuGet: Microsoft ASP.NET Identity Core.
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Nancy.Json;
using YeetPostV1_4.DataModel;
//master



namespace YeetPostV1_4.Controllers
{
    public class YeetController : Controller
    {
        private readonly ILogger<YeetController> _logger;
        private readonly YeetServices _yeetServices = new YeetServices();
        private readonly AccountServices _accountServices = new AccountServices();
        public string location;
        private string userId;

        public YeetController(ILogger<YeetController> logger)
        {
            _logger = logger;

        }


        public IActionResult Index()
        {
            bool isAuthenticated = User.Identity.IsAuthenticated;
            var x = 2;

            if (!isAuthenticated)
            {
                return RedirectToPage("/Account/Login", new { area = "Identity" });
            }


            string userId = getUserId();
            var status = _accountServices.getStatus(userId);
            if(status == "banned")
            {
                return RedirectToAction("Banned", "Status");
            }

            var model = new YeetViewModel();
            location = _accountServices.getLocation(userId);
            
            model.yeets = _yeetServices.GetYeetsByNew(location, userId);
            model.status = "new";
            

            model.location = location;

            //return RedirectToAction("ViewComments", "Comment", new { yeetID = "ZFfMisCGPO0I7sK1HaDE" });

            return View(model);
        }

        public string getUserId()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);

            return claim.Value;

        }




        [HttpPost]
        public string pushNewYeet(string header, string yeet, string location)
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);

            string name = User.Identity.Name;

            //put into a class later and pass it through much cleaner
            userId = claim.Value;

           

            _yeetServices.newYeet(header, yeet, location, userId, name);

            var model = new YeetViewModel();
            model.yeets = _yeetServices.GetYeetsByNew(location, userId);
            model.location = location;


            var x = JsonConvert.SerializeObject(model);

            return x;
        }


        [HttpGet]
        public string filterBy(string location, string byWhat)
        {
            

            //put into a class later and pass it through much cleaner
            userId = getUserId();


            var model = new YeetViewModel();
            if (byWhat == "new")
            { 
                model.yeets = _yeetServices.GetYeetsByNew(location, userId);
                model.status = "new";
            }
            else if(byWhat == "trending")
            {
                model.yeets = _yeetServices.GetYeetsByTrend(location, userId);
                model.status = "trending";

            }
            //set it to 0
            //if(model.yeets.Count() == 0)
            //{
            //    model.yeets = new List<Yeet>();
            //    model.yeets.Add(new Yeet(
                    
            //        ));
            //}

            model.location = location;

            

            return new JavaScriptSerializer().Serialize(model);
        }



        public string getYeets(string location)
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);

            string name = User.Identity.Name;

            //put into a class later and pass it through much cleaner
            userId = claim.Value;

            var model = new YeetViewModel();
            model.yeets = _yeetServices.GetYeetsByNew(location, userId);
            model.status = "new";

            return new JavaScriptSerializer().Serialize(model);
        }


        public string deleteYeet(string yeetId, string location, string status, string from)
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);

            string name = User.Identity.Name;

            //put into a class later and pass it through much cleaner
            userId = claim.Value;
            _yeetServices.deleteYeet(yeetId);


            var model = new YeetViewModel();
            
            model.yeets = (status == "new") ? _yeetServices.GetYeetsByNew(location, userId) : _yeetServices.GetYeetsByTrend(location, userId);
            model.status = status;
            //from profile return to profile
            model.yeets = (from == "profile") ? _yeetServices.GetYeetsById(userId) : model.yeets;

            


            return new JavaScriptSerializer().Serialize(model);
        }



        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

YeetPostV1_4/YeetPostV1_4/Views/Shared/_CreateYeet.cshtml
@model YeetPostV1_4.ViewModel.YeetViewModel

<v-col cols="8">
    <v-card max-width="550">
        <v-form ref="form" v-on:submit.prevent="submit">
            <v-container fluid>
                <v-row>



                    <v-col cols="12">
                        <v-text-field v-model="header"
                                      id="header"
                                      :rules="rules.name"
                                      color="purple darken-2"
                                      label="Yeet Topic"
                                      required></v-text-field>
                    </v-col>


                    <v-col cols="12">
                        <v-textarea v-model="yeet"
                                    id="yeet"
                                    rows="3"
                                    :rules="rules.name"
                                    color="teal">
                            <template v-slot:label>
                                <div>
                                    Yeet <small>(make it funny)</small>
                                </div>
                            </template>
                        </v-textarea>
                    </v-col>
                    <v-col cols="12">
                        <v-file-input  show-size label="File input"
                                     id="file"
                                      v-model="file"
                                      v-on:change="onchange()" 
                                      ></v-file-input>
                    </v-col>
                    <v-col cols="8">

                    </v-col>


                    <v-col cols="8">
                        <v-btn v-on:click="submit">Post</v-btn>
                    </v-col>

                </v-row>
            </v-container>
        </v-form>
    </v-card>

</v-col>

YeetPostV1_4/YeetPostV1_4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - YeetPostV1_4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />


    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons" rel="stylesheet">

    @*<link href="https://cdnjs.cloudflare.com/ajax/libs/vuetify/1.5.14/vuetify.css" rel="stylesheet">*@
    <link href="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.min.css" rel="stylesheet">

    @{string link = "https://cdn.jsdelivr.net/npm/@mdi/font@4.x/css/materialdesignicons.min.css";
        <link href="@link" rel="stylesheet">
    }



    <script src="https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Yeet" asp-action="Index">YeetPostV1_4</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - YeetPostV1_4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="~/js/vue.js"></script>


   

    @RenderSection("Scripts", required: false)
</body>
</html>

YeetPostV1_4/YeetPostV1_4/Views/Shared/_YeetPartial.cshtml
@model YeetPostV1_4.ViewModel.YeetViewModel;

<v-app id="inspire">
    <div v-for="(yeet, index) in model.yeets">
        <v-card class="mx-auto"
                color="#26c6da"
                dark
                max-width="600">
            <div>
                <v-card-title>


                    <v-list-item-content>
                        <v-list-item-title> &nbsp; {{yeet.username}}</v-list-item-title>
                    </v-list-item-content>

                    <v-list-item-content>
                        <v-list-item-title> &nbsp; <strong> <b>{{yeet.header}}</b> </strong></v-list-item-title>
                    </v-list-item-content>
                    <v-list-item-content>
                        <v-list-item-title> &nbsp; {{yeet.date}}</v-list-item-title>
                    </v-list-item-content>

                    <v-list-item-content>
                        <v-list-item-title> &nbsp; {{yeet.location}}</v-list-item-title>
                    </v-list-item-content>


                    <v-dialog v-if="yeet.isMine == true" v-model="yeet.deleteModal" persistent max-width="290">
                        <template v-slot:activator="{ on }">
                            <v-list-item-content>
                                <v-icon class="mr-1" color="red" v-on="on">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; mdi-delete</v-icon>
                            </v-list-item-content>
                        </template>
                        <v-card>
                            <div>
                                <v-card-title class="headline" style="text-align: center;">Are you sure you want to deYeet this Yeet?</v-card-title>
                                <v-card-actions>
                                    <v-spacer></v-spacer>
                                    <v-btn color="green darken-1" text v-on:click="yeet.deleteModal = false">Close</v-btn>
                                    <v-btn color="green darken-1" text
                                           v-on:click="deleteYeet(yeet.yeetID, yeet.location)">Yes</v-btn>
                                </v-card-actions>
                            </div>
                            <div>

                            </div>
                        </v-card>
                    </v-dialog>

                    <v-dialog v-if="yeet.iFlagged == true && yeet.isMine == false" v-model="yeet.modal" persistent max-width="290">
                        <template v-slot:activator="{ on }">
                            <v-list-item-content>
                                <v-icon class="mr-1" color="red" v-on="on">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; mdi-flag</v-icon>

                            </v-list-item-content>
                        </template>
                        <v-card>
                            <div>
                                <v-card-title class="headline" style="text-align: center;">Unflag Yeet? {{yeet.yeetID}}</v-card-title>

                                <v-card-actions>
                                    <v-spacer></v-spacer>
                                    <v-btn color="green darken-1" text v-on:click="yeet.modal = false">Close</v-btn>
                                    <v-btn color="green darken-1" text
                                           v-on:click="flagYeet(yeet.yeetID, yeet.whoFlags,true, inappropriate, model.location )">Yes</v-btn>
                                </v-card-actions>
                            </div>
                            <div>

                            </div>
                        </v-card>
                    </v-dialog>

                    <v-dialog v-model="yeet.modal" persistent max-width="290" v-if="yeet.iFlagged == false && yeet.isMine == false">
                        <template v-slot:activator="{ on }">
                            <v-list-item-content>

                                <v-icon class="mr-1" color="white" v-on="on">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; mdi-flag</v-icon>
                            </v-list-item-content>
                        </template>
                        <v-card>
                            <v-card-title class="headline" style="text-align: center;">Flag for What?</v-card-title>

                            <v-row>
                                <v-col cols="12">
                                    <v-divider></v-divider>
                                    <v-card-text style="font-size: 32px; text-align: center;"
                                                 v-on:click="flagYeet(yeet.yeetID, yeet.whoFlags,false, inappropriate ,model.location )">Innapropriate Context</v-card-text>
                                    <v-divider></v-divider>
                                </v-col>
                                <v-col cols="12">
                                    <v-card-text style="font-size: 32px;text-align: center;"
                                                 v-on:click="flagYeet(yeet.yeetID, yeet.whoFlags,false, abusive ,model.location )">Abusive</v-card-text>
                                    <v-divider></v-divider>
                                </v-col>

                            </v-row>
                            <v-card-actions>
                                <v-spacer></v-spacer>
                                <v-btn color="green darken-1" text v-on:click="yeet.modal = false">Close</v-btn>
                            </v-card-actions>
                        </v-card>
                    </v-dialog>


                </v-card-title>

                <v-card-text class="headline font-weight-bold" v-on:click="viewYeet(yeet.yeetID)">
                    "   {{yeet.yeet}} "
                </v-card-text>
            </div>
            <v-card-actions>
                <v-list-item class="grow">

                    <v-row align="center"
                           justify="end">
                        <v-icon class="mr-1" color="red" v-if="yeet.iLiked == true" v-on:click="likeYeet(yeet.yeetID, yeet.whoLikes, model.location, true)">mdi-heart</v-icon>

                        <v-icon class="mr-1" v-else v-on:click="likeYeet(yeet.yeetID, yeet.whoLikes, model.location, false)">mdi-heart</v-icon>


                        <span class="subheading mr-2">{{yeet.totalLikes}}</span>

                    </v-row>
                </v-list-item>
            </v-card-actions>

        </v-card>
        <br />
    </div>
</v-app>

YeetPostV1_4/YeetPostV1_4/Views/Shared/_YeetTabs.cshtml
<v-col cols="2">
    <v-tabs vertical>
        <v-tab v-on:click="filterBy('new', model.location, false)">
            @*<v-icon left>mdi-octagram</v-icon>*@
            New
        </v-tab>
        <v-tab v-on:click="filterBy('trending', model.location, false)">
            @*<v-icon left>mdi-fire</v-icon>*@
            Trending
        </v-tab>
        <v-select   v-model="select"
                    :items="location"
                    v-on:change="filterBy('trending', select, true)"
                    label="Select a City"
                    ></v-select>
      


    </v-tabs>
</v-col>
<v-col cols="2">

</v-col>